### ISSUE TITLE
Code issue

### ISSUE THREAD

**Issue by tanxiaoke6** [Necolizer/CHASE#1]
Congratulations on your acceptance into NeurIPS 2024! Your achievement is truly outstanding, and I believe it will greatly contribute to the advancement of skeleton-based action recognition. Thank you for making your code open-source. I have a few questions regarding your code. In the configuration files you provided, the model seems identical to the original method's model. Specifically, taking ctrgcn as an example, the Model has undergone minimal changes, but there is an additional Model_GROUP. Therefore, I would like to inquire about where the code related to the CHASE method has been added.

**Comment by Necolizer** [comment]
Hi, hope the following clarifications may help:
- In configuration files, you could see the configurations of a CHASE wrapper for each backbone (e.g., line 32-40 in [this config](https://github.com/Necolizer/CHASE/blob/main/config/CTRGCN/ntu26/ntu26_xsub_joint_chase.yaml)). The related implementation is in [this script](https://github.com/Necolizer/CHASE/blob/main/model/Wrapper/chas.py).
- In configuration files, you could also see that we use a different training objective (e.g., line 60-62 in [this config](https://github.com/Necolizer/CHASE/blob/main/config/CTRGCN/ntu26/ntu26_xsub_joint_chase.yaml)). The related implementation is in [this script](https://github.com/Necolizer/CHASE/blob/main/utils/loss.py).
- Model_GROUPs are adpatations for group activity recognition tasks.

**Comment by tanxiaoke6** [comment]
OK, thank you for your reply.
